modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
logoFile="iclogo.png"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[1.20.1-10.2.0-182,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "farmersdelight"
mandatory = false
versionRange = "[1.20.1-1.2,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "jei"
mandatory = false
versionRange = "[15.20.0.127,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "vinery"
mandatory = false
versionRange = "[1.4.40,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "jade"
mandatory = false
versionRange = "[11.13.2,)"
ordering = "AFTER"
side = "BOTH"